/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class PageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Page");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cGeolocalisationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cGeolocalisationGeolocalisationKeyword_0_0 = (Keyword)cGeolocalisationAssignment_0.eContents().get(0);
		private final Keyword cPageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cDescriptionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionEStringParserRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Keyword cMailKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cMailAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cMailEStringParserRuleCall_6_0 = (RuleCall)cMailAssignment_6.eContents().get(0);
		private final Keyword cTelephoneKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTelephoneAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTelephoneEStringParserRuleCall_8_0 = (RuleCall)cTelephoneAssignment_8.eContents().get(0);
		private final Keyword cMenuKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cMenuAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cMenuSourceMenuEnumRuleCall_10_0 = (RuleCall)cMenuAssignment_10.eContents().get(0);
		private final Keyword cSelectionKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cSelectionAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cSelectionSourceSelectionEnumRuleCall_12_0 = (RuleCall)cSelectionAssignment_12.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cHeure_ouvertureKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cHeure_ouvertureAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cHeure_ouvertureEIntParserRuleCall_13_1_0 = (RuleCall)cHeure_ouvertureAssignment_13_1.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cHeure_fermetureKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cHeure_fermetureAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cHeure_fermetureEIntParserRuleCall_14_1_0 = (RuleCall)cHeure_fermetureAssignment_14_1.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cNb_PersKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cNb_PersAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cNb_PersEIntParserRuleCall_15_1_0 = (RuleCall)cNb_PersAssignment_15_1.eContents().get(0);
		private final Keyword cPresentationKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cPresentationAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cPresentationSourcePresEnumRuleCall_17_0 = (RuleCall)cPresentationAssignment_17.eContents().get(0);
		private final Keyword cLogoKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Assignment cLogoAssignment_19 = (Assignment)cGroup.eContents().get(19);
		private final RuleCall cLogoSourceLogoEnumRuleCall_19_0 = (RuleCall)cLogoAssignment_19.eContents().get(0);
		private final Keyword cSourceKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Assignment cSourceAssignment_21 = (Assignment)cGroup.eContents().get(21);
		private final RuleCall cSourceSourceParserRuleCall_21_0 = (RuleCall)cSourceAssignment_21.eContents().get(0);
		private final Group cGroup_22 = (Group)cGroup.eContents().get(22);
		private final Keyword cCommaKeyword_22_0 = (Keyword)cGroup_22.eContents().get(0);
		private final Assignment cSourceAssignment_22_1 = (Assignment)cGroup_22.eContents().get(1);
		private final RuleCall cSourceSourceParserRuleCall_22_1_0 = (RuleCall)cSourceAssignment_22_1.eContents().get(0);
		private final Group cGroup_23 = (Group)cGroup.eContents().get(23);
		private final Keyword cPort_backKeyword_23_0 = (Keyword)cGroup_23.eContents().get(0);
		private final Assignment cPort_backAssignment_23_1 = (Assignment)cGroup_23.eContents().get(1);
		private final RuleCall cPort_backEIntParserRuleCall_23_1_0 = (RuleCall)cPort_backAssignment_23_1.eContents().get(0);
		private final Group cGroup_24 = (Group)cGroup.eContents().get(24);
		private final Keyword cPort_frontKeyword_24_0 = (Keyword)cGroup_24.eContents().get(0);
		private final Assignment cPort_frontAssignment_24_1 = (Assignment)cGroup_24.eContents().get(1);
		private final RuleCall cPort_frontEIntParserRuleCall_24_1_0 = (RuleCall)cPort_frontAssignment_24_1.eContents().get(0);
		
		//Page:
		//	geolocalisation?='geolocalisation'?
		//	'Page'
		//	name=EString
		//	'description' description=EString
		//	'mail' mail=EString
		//	'telephone' telephone=EString
		//	'menu' menu=SourceMenu
		//	'Selection' Selection=SourceSelection ('heure_ouverture' heure_ouverture=EInt)? ('heure_fermeture'
		//	heure_fermeture=EInt)? ('nb_Pers' nb_Pers=EInt)?
		//	'presentation' presentation=SourcePres
		//	'logo' logo=SourceLogo
		//	'source' source+=Source ("," source+=Source)* ('Port_back' Port_back=EInt)? ('Port_front' Port_front=EInt)?;
		@Override public ParserRule getRule() { return rule; }
		
		//geolocalisation?='geolocalisation'? 'Page' name=EString 'description' description=EString 'mail' mail=EString
		//'telephone' telephone=EString 'menu' menu=SourceMenu 'Selection' Selection=SourceSelection ('heure_ouverture'
		//heure_ouverture=EInt)? ('heure_fermeture' heure_fermeture=EInt)? ('nb_Pers' nb_Pers=EInt)? 'presentation'
		//presentation=SourcePres 'logo' logo=SourceLogo 'source' source+=Source ("," source+=Source)* ('Port_back'
		//Port_back=EInt)? ('Port_front' Port_front=EInt)?
		public Group getGroup() { return cGroup; }
		
		//geolocalisation?='geolocalisation'?
		public Assignment getGeolocalisationAssignment_0() { return cGeolocalisationAssignment_0; }
		
		//'geolocalisation'
		public Keyword getGeolocalisationGeolocalisationKeyword_0_0() { return cGeolocalisationGeolocalisationKeyword_0_0; }
		
		//'Page'
		public Keyword getPageKeyword_1() { return cPageKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'description'
		public Keyword getDescriptionKeyword_3() { return cDescriptionKeyword_3; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_0() { return cDescriptionEStringParserRuleCall_4_0; }
		
		//'mail'
		public Keyword getMailKeyword_5() { return cMailKeyword_5; }
		
		//mail=EString
		public Assignment getMailAssignment_6() { return cMailAssignment_6; }
		
		//EString
		public RuleCall getMailEStringParserRuleCall_6_0() { return cMailEStringParserRuleCall_6_0; }
		
		//'telephone'
		public Keyword getTelephoneKeyword_7() { return cTelephoneKeyword_7; }
		
		//telephone=EString
		public Assignment getTelephoneAssignment_8() { return cTelephoneAssignment_8; }
		
		//EString
		public RuleCall getTelephoneEStringParserRuleCall_8_0() { return cTelephoneEStringParserRuleCall_8_0; }
		
		//'menu'
		public Keyword getMenuKeyword_9() { return cMenuKeyword_9; }
		
		//menu=SourceMenu
		public Assignment getMenuAssignment_10() { return cMenuAssignment_10; }
		
		//SourceMenu
		public RuleCall getMenuSourceMenuEnumRuleCall_10_0() { return cMenuSourceMenuEnumRuleCall_10_0; }
		
		//'Selection'
		public Keyword getSelectionKeyword_11() { return cSelectionKeyword_11; }
		
		//Selection=SourceSelection
		public Assignment getSelectionAssignment_12() { return cSelectionAssignment_12; }
		
		//SourceSelection
		public RuleCall getSelectionSourceSelectionEnumRuleCall_12_0() { return cSelectionSourceSelectionEnumRuleCall_12_0; }
		
		//('heure_ouverture' heure_ouverture=EInt)?
		public Group getGroup_13() { return cGroup_13; }
		
		//'heure_ouverture'
		public Keyword getHeure_ouvertureKeyword_13_0() { return cHeure_ouvertureKeyword_13_0; }
		
		//heure_ouverture=EInt
		public Assignment getHeure_ouvertureAssignment_13_1() { return cHeure_ouvertureAssignment_13_1; }
		
		//EInt
		public RuleCall getHeure_ouvertureEIntParserRuleCall_13_1_0() { return cHeure_ouvertureEIntParserRuleCall_13_1_0; }
		
		//('heure_fermeture' heure_fermeture=EInt)?
		public Group getGroup_14() { return cGroup_14; }
		
		//'heure_fermeture'
		public Keyword getHeure_fermetureKeyword_14_0() { return cHeure_fermetureKeyword_14_0; }
		
		//heure_fermeture=EInt
		public Assignment getHeure_fermetureAssignment_14_1() { return cHeure_fermetureAssignment_14_1; }
		
		//EInt
		public RuleCall getHeure_fermetureEIntParserRuleCall_14_1_0() { return cHeure_fermetureEIntParserRuleCall_14_1_0; }
		
		//('nb_Pers' nb_Pers=EInt)?
		public Group getGroup_15() { return cGroup_15; }
		
		//'nb_Pers'
		public Keyword getNb_PersKeyword_15_0() { return cNb_PersKeyword_15_0; }
		
		//nb_Pers=EInt
		public Assignment getNb_PersAssignment_15_1() { return cNb_PersAssignment_15_1; }
		
		//EInt
		public RuleCall getNb_PersEIntParserRuleCall_15_1_0() { return cNb_PersEIntParserRuleCall_15_1_0; }
		
		//'presentation'
		public Keyword getPresentationKeyword_16() { return cPresentationKeyword_16; }
		
		//presentation=SourcePres
		public Assignment getPresentationAssignment_17() { return cPresentationAssignment_17; }
		
		//SourcePres
		public RuleCall getPresentationSourcePresEnumRuleCall_17_0() { return cPresentationSourcePresEnumRuleCall_17_0; }
		
		//'logo'
		public Keyword getLogoKeyword_18() { return cLogoKeyword_18; }
		
		//logo=SourceLogo
		public Assignment getLogoAssignment_19() { return cLogoAssignment_19; }
		
		//SourceLogo
		public RuleCall getLogoSourceLogoEnumRuleCall_19_0() { return cLogoSourceLogoEnumRuleCall_19_0; }
		
		//'source'
		public Keyword getSourceKeyword_20() { return cSourceKeyword_20; }
		
		//source+=Source
		public Assignment getSourceAssignment_21() { return cSourceAssignment_21; }
		
		//Source
		public RuleCall getSourceSourceParserRuleCall_21_0() { return cSourceSourceParserRuleCall_21_0; }
		
		//("," source+=Source)*
		public Group getGroup_22() { return cGroup_22; }
		
		//","
		public Keyword getCommaKeyword_22_0() { return cCommaKeyword_22_0; }
		
		//source+=Source
		public Assignment getSourceAssignment_22_1() { return cSourceAssignment_22_1; }
		
		//Source
		public RuleCall getSourceSourceParserRuleCall_22_1_0() { return cSourceSourceParserRuleCall_22_1_0; }
		
		//('Port_back' Port_back=EInt)?
		public Group getGroup_23() { return cGroup_23; }
		
		//'Port_back'
		public Keyword getPort_backKeyword_23_0() { return cPort_backKeyword_23_0; }
		
		//Port_back=EInt
		public Assignment getPort_backAssignment_23_1() { return cPort_backAssignment_23_1; }
		
		//EInt
		public RuleCall getPort_backEIntParserRuleCall_23_1_0() { return cPort_backEIntParserRuleCall_23_1_0; }
		
		//('Port_front' Port_front=EInt)?
		public Group getGroup_24() { return cGroup_24; }
		
		//'Port_front'
		public Keyword getPort_frontKeyword_24_0() { return cPort_frontKeyword_24_0; }
		
		//Port_front=EInt
		public Assignment getPort_frontAssignment_24_1() { return cPort_frontAssignment_24_1; }
		
		//EInt
		public RuleCall getPort_frontEIntParserRuleCall_24_1_0() { return cPort_frontEIntParserRuleCall_24_1_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class SourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Source");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSourceAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSourceNameEnumRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Source:
		//	{Source} name=SourceName?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Source} name=SourceName?
		public Group getGroup() { return cGroup; }
		
		//{Source}
		public Action getSourceAction_0() { return cSourceAction_0; }
		
		//name=SourceName?
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//SourceName
		public RuleCall getNameSourceNameEnumRuleCall_1_0() { return cNameSourceNameEnumRuleCall_1_0; }
	}
	public class EBooleanObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EBooleanObject");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBooleanObject ecore::EBooleanObject:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	public class SourceMenuElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SourceMenu");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSideBarEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSideBarSideBarKeyword_0_0 = (Keyword)cSideBarEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNavBarEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNavBarNavBarKeyword_1_0 = (Keyword)cNavBarEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum SourceMenu:
		//	SideBar | NavBar;
		public EnumRule getRule() { return rule; }
		
		//SideBar | NavBar
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SideBar
		public EnumLiteralDeclaration getSideBarEnumLiteralDeclaration_0() { return cSideBarEnumLiteralDeclaration_0; }
		
		//'SideBar'
		public Keyword getSideBarSideBarKeyword_0_0() { return cSideBarSideBarKeyword_0_0; }
		
		//NavBar
		public EnumLiteralDeclaration getNavBarEnumLiteralDeclaration_1() { return cNavBarEnumLiteralDeclaration_1; }
		
		//'NavBar'
		public Keyword getNavBarNavBarKeyword_1_0() { return cNavBarNavBarKeyword_1_0; }
	}
	public class SourceSelectionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SourceSelection");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPlanningEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPlanningPlanningKeyword_0_0 = (Keyword)cPlanningEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cRDVEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cRDVRDVKeyword_1_0 = (Keyword)cRDVEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum SourceSelection:
		//	Planning | RDV;
		public EnumRule getRule() { return rule; }
		
		//Planning | RDV
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Planning
		public EnumLiteralDeclaration getPlanningEnumLiteralDeclaration_0() { return cPlanningEnumLiteralDeclaration_0; }
		
		//'Planning'
		public Keyword getPlanningPlanningKeyword_0_0() { return cPlanningPlanningKeyword_0_0; }
		
		//RDV
		public EnumLiteralDeclaration getRDVEnumLiteralDeclaration_1() { return cRDVEnumLiteralDeclaration_1; }
		
		//'RDV'
		public Keyword getRDVRDVKeyword_1_0() { return cRDVRDVKeyword_1_0; }
	}
	public class SourcePresElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SourcePres");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBasiqueEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBasiqueBasiqueKeyword_0_0 = (Keyword)cBasiqueEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCardEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCardCardKeyword_1_0 = (Keyword)cCardEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum SourcePres:
		//	basique | card;
		public EnumRule getRule() { return rule; }
		
		//basique | card
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//basique
		public EnumLiteralDeclaration getBasiqueEnumLiteralDeclaration_0() { return cBasiqueEnumLiteralDeclaration_0; }
		
		//'basique'
		public Keyword getBasiqueBasiqueKeyword_0_0() { return cBasiqueBasiqueKeyword_0_0; }
		
		//card
		public EnumLiteralDeclaration getCardEnumLiteralDeclaration_1() { return cCardEnumLiteralDeclaration_1; }
		
		//'card'
		public Keyword getCardCardKeyword_1_0() { return cCardCardKeyword_1_0; }
	}
	public class SourceLogoElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SourceLogo");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cComuteEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cComuteComuteKeyword_0_0 = (Keyword)cComuteEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cRdvEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cRdvRdvKeyword_1_0 = (Keyword)cRdvEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cTrajetEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cTrajetTrajetKeyword_2_0 = (Keyword)cTrajetEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum SourceLogo:
		//	comute | rdv | trajet;
		public EnumRule getRule() { return rule; }
		
		//comute | rdv | trajet
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//comute
		public EnumLiteralDeclaration getComuteEnumLiteralDeclaration_0() { return cComuteEnumLiteralDeclaration_0; }
		
		//'comute'
		public Keyword getComuteComuteKeyword_0_0() { return cComuteComuteKeyword_0_0; }
		
		//rdv
		public EnumLiteralDeclaration getRdvEnumLiteralDeclaration_1() { return cRdvEnumLiteralDeclaration_1; }
		
		//'rdv'
		public Keyword getRdvRdvKeyword_1_0() { return cRdvRdvKeyword_1_0; }
		
		//trajet
		public EnumLiteralDeclaration getTrajetEnumLiteralDeclaration_2() { return cTrajetEnumLiteralDeclaration_2; }
		
		//'trajet'
		public Keyword getTrajetTrajetKeyword_2_0() { return cTrajetTrajetKeyword_2_0; }
	}
	public class SourceNameElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SourceName");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTisseoEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTisseoTisseoKeyword_0_0 = (Keyword)cTisseoEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cGoogleMapEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cGoogleMapGoogleMapKeyword_1_0 = (Keyword)cGoogleMapEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum SourceName:
		//	Tisseo | GoogleMap;
		public EnumRule getRule() { return rule; }
		
		//Tisseo | GoogleMap
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Tisseo
		public EnumLiteralDeclaration getTisseoEnumLiteralDeclaration_0() { return cTisseoEnumLiteralDeclaration_0; }
		
		//'Tisseo'
		public Keyword getTisseoTisseoKeyword_0_0() { return cTisseoTisseoKeyword_0_0; }
		
		//GoogleMap
		public EnumLiteralDeclaration getGoogleMapEnumLiteralDeclaration_1() { return cGoogleMapEnumLiteralDeclaration_1; }
		
		//'GoogleMap'
		public Keyword getGoogleMapGoogleMapKeyword_1_0() { return cGoogleMapGoogleMapKeyword_1_0; }
	}
	
	private final PageElements pPage;
	private final EStringElements pEString;
	private final SourceElements pSource;
	private final SourceMenuElements eSourceMenu;
	private final SourceSelectionElements eSourceSelection;
	private final SourcePresElements eSourcePres;
	private final SourceLogoElements eSourceLogo;
	private final EBooleanObjectElements pEBooleanObject;
	private final EIntElements pEInt;
	private final SourceNameElements eSourceName;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPage = new PageElements();
		this.pEString = new EStringElements();
		this.pSource = new SourceElements();
		this.eSourceMenu = new SourceMenuElements();
		this.eSourceSelection = new SourceSelectionElements();
		this.eSourcePres = new SourcePresElements();
		this.eSourceLogo = new SourceLogoElements();
		this.pEBooleanObject = new EBooleanObjectElements();
		this.pEInt = new EIntElements();
		this.eSourceName = new SourceNameElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Page:
	//	geolocalisation?='geolocalisation'?
	//	'Page'
	//	name=EString
	//	'description' description=EString
	//	'mail' mail=EString
	//	'telephone' telephone=EString
	//	'menu' menu=SourceMenu
	//	'Selection' Selection=SourceSelection ('heure_ouverture' heure_ouverture=EInt)? ('heure_fermeture'
	//	heure_fermeture=EInt)? ('nb_Pers' nb_Pers=EInt)?
	//	'presentation' presentation=SourcePres
	//	'logo' logo=SourceLogo
	//	'source' source+=Source ("," source+=Source)* ('Port_back' Port_back=EInt)? ('Port_front' Port_front=EInt)?;
	public PageElements getPageAccess() {
		return pPage;
	}
	
	public ParserRule getPageRule() {
		return getPageAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Source:
	//	{Source} name=SourceName?;
	public SourceElements getSourceAccess() {
		return pSource;
	}
	
	public ParserRule getSourceRule() {
		return getSourceAccess().getRule();
	}
	
	//enum SourceMenu:
	//	SideBar | NavBar;
	public SourceMenuElements getSourceMenuAccess() {
		return eSourceMenu;
	}
	
	public EnumRule getSourceMenuRule() {
		return getSourceMenuAccess().getRule();
	}
	
	//enum SourceSelection:
	//	Planning | RDV;
	public SourceSelectionElements getSourceSelectionAccess() {
		return eSourceSelection;
	}
	
	public EnumRule getSourceSelectionRule() {
		return getSourceSelectionAccess().getRule();
	}
	
	//enum SourcePres:
	//	basique | card;
	public SourcePresElements getSourcePresAccess() {
		return eSourcePres;
	}
	
	public EnumRule getSourcePresRule() {
		return getSourcePresAccess().getRule();
	}
	
	//enum SourceLogo:
	//	comute | rdv | trajet;
	public SourceLogoElements getSourceLogoAccess() {
		return eSourceLogo;
	}
	
	public EnumRule getSourceLogoRule() {
		return getSourceLogoAccess().getRule();
	}
	
	//EBooleanObject ecore::EBooleanObject:
	//	'true' | 'false';
	public EBooleanObjectElements getEBooleanObjectAccess() {
		return pEBooleanObject;
	}
	
	public ParserRule getEBooleanObjectRule() {
		return getEBooleanObjectAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//enum SourceName:
	//	Tisseo | GoogleMap;
	public SourceNameElements getSourceNameAccess() {
		return eSourceName;
	}
	
	public EnumRule getSourceNameRule() {
		return getSourceNameAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
