/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import dSLMobility.Page;
import dSLMobility.Source;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;
  
  protected void _format(final Page page, @Extension final IFormattableDocument document) {
    EList<Source> _source = page.getSource();
    for (final Source source : _source) {
      document.<Source>format(source);
    }
  }
  
  public void format(final Object page, final IFormattableDocument document) {
    if (page instanceof XtextResource) {
      _format((XtextResource)page, document);
      return;
    } else if (page instanceof Page) {
      _format((Page)page, document);
      return;
    } else if (page instanceof EObject) {
      _format((EObject)page, document);
      return;
    } else if (page == null) {
      _format((Void)null, document);
      return;
    } else if (page != null) {
      _format(page, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(page, document).toString());
    }
  }
}
